Tickets/dm 25150
lsst-ts/ts_config_attcs pull request #12
Opened 2020-08-18 18:51 UTC by patrickingraham

Revs the version to add wavelength focus relationship. Note that only recent configuration files were updated.

2020-09-10 21:23 UTC, tribeiro commented on ATAOS/v3/hex_m1_hex_202003_v3.yaml
> +  - 0.0
add newline at the end of the file

2020-09-10 21:25 UTC, tribeiro commented on ATAOS/v3/_labels.yaml
> +current: hex_m1_hex_202003.yaml
I think the names of the files are wrong here should be:

```
current : hex_m1_hex_202003_v3.yaml
constant_hex : hex_m1_202003_constant_hex_v3.yaml
```

They are missing a `_v3`

2020-09-10 21:25 UTC, tribeiro requested changes
Please, correct the labels file!

2020-09-22 17:32 UTC, patrickingraham commented
Changes made. Also re-based on develop.

2020-10-01 18:42 UTC, tribeiro approved these changes

2020-10-01 18:43 UTC, merged